/*
 * JS for Calendar generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '96bf557e-32e1-4d20-ac3a-5655fb026817';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Club",
    "location": "Club.html"
}, {
    "name": "GitHub_Img",
    "location": "GitHub_Img.html"
}, {
    "name": "GitHub_File",
    "location": "GitHub_File.html"
}, {
    "name": "ExamplePage1426375367500",
    "location": "ExamplePage1426375367500.html"
}, {
    "name": "GitHub_Gist",
    "location": "GitHub_Gist.html"
}, {
    "name": "me",
    "location": "me.html"
}, {
    "name": "GitHub_Repo",
    "location": "GitHub_Repo.html"
}, {
    "name": "Notify",
    "location": "Notify.html"
}, {
    "name": "signIn",
    "location": "signIn.html"
}, {
    "name": "Calendar",
    "location": "Calendar.html"
}, {
    "name": "signUp",
    "location": "signUp.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "Notifications",
    "location": "Notifications.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "GitHub_Git",
    "location": "GitHub_Git.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "GitHub_Search",
    "location": "GitHub_Search.html"
}, {
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}, {
    "name": "yourEvents",
    "location": "yourEvents.html"
}];


function Calendar_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'logout': 'Calendar_logout',
        'club': 'Calendar_club',
        'metab': 'Calendar_metab',
        'notify': 'Calendar_notify',
        'calendar': 'Calendar_calendar'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Calendar_logout_clone_4_onsuccess_mapping_0"] = {
        "homeScreen": "Calendar",
        "directions": []
    };

    Apperyio.mappings["Calendar_logout_clone_4_onbeforesend_mapping_0"] = {
        "homeScreen": "Calendar",
        "directions": [

        {
            "from_name": "userSessionToken",
            "from_type": "SESSION_STORAGE",

            "to_name": "logout_clone_4",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['X-Appery-Session-Token']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.logout_clone_4 = Apperyio.datasources.logout_clone_4 = new Apperyio.DataSource(UserInformation_logout_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Calendar_logout_clone_4_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("Calendar");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Calendar_logout_clone_4_onsuccess_mapping_0"]);
            Apperyio.navigateTo('startScreen', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'Calendar';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Calendar_onLoad = function() {
            Calendar_elementsExtraJS();

            Calendar_deviceEvents();
            Calendar_windowEvents();
            Calendar_elementsEvents();
        };

    // screen window events


    function Calendar_windowEvents() {

        $('#Calendar').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Calendar_deviceEvents() {
        document.addEventListener("deviceready", function() {

            $(document).bind("resume", function() {
                PushNotification.getPendingNotifications(function(status) {
                    var notifications = status.notifications;
                    for (var i = 0; i < notifications.length; ++i) {
                        PushNotification.notificationCallback(notifications[i]);
                    }
                });
            });

        });
    };

    // screen elements extra js


    function Calendar_elementsExtraJS() {
        // screen (Calendar) extra code

    };

    // screen elements handler


    function Calendar_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Calendar_mobileheader [name="logout"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        logout_clone_4.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#Calendar_mobileheader [name="logout"]');

        $(document).off("click", '#Calendar_mobilefooter [name="metab"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Club', {
                        reverse: false
                    });

                }
            },
        }, '#Calendar_mobilefooter [name="metab"]');
        $(document).off("click", '#Calendar_mobilefooter [name="notify"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    setTimeout(function() {
                        window.location = 'Notify.html';
                    }, 0);

                }
            },
        }, '#Calendar_mobilefooter [name="notify"]');
        $(document).off("click", '#Calendar_mobilefooter [name="calendar"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    setTimeout(function() {
                        window.location = 'Calendar.html';
                    }, 0);

                }
            },
        }, '#Calendar_mobilefooter [name="calendar"]');

    };

    $(document).off("pagebeforeshow", "#Calendar").on("pagebeforeshow", "#Calendar", function(event, ui) {
        Apperyio.CurrentScreen = "Calendar";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Calendar_onLoad();
};

$(document).off("pagecreate", "#Calendar").on("pagecreate", "#Calendar", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Calendar_js();
});