/*
 * JS for Club generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    alert("hello");
    return '96bf557e-32e1-4d20-ac3a-5655fb026817';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Club",
    "location": "Club.html"
}, {
    "name": "GitHub_Img",
    "location": "GitHub_Img.html"
}, {
    "name": "GitHub_File",
    "location": "GitHub_File.html"
}, {
    "name": "ExamplePage1426375367500",
    "location": "ExamplePage1426375367500.html"
}, {
    "name": "GitHub_Gist",
    "location": "GitHub_Gist.html"
}, {
    "name": "me",
    "location": "me.html"
}, {
    "name": "GitHub_Repo",
    "location": "GitHub_Repo.html"
}, {
    "name": "Notify",
    "location": "Notify.html"
}, {
    "name": "signIn",
    "location": "signIn.html"
}, {
    "name": "Calendar",
    "location": "Calendar.html"
}, {
    "name": "signUp",
    "location": "signUp.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "Notifications",
    "location": "Notifications.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "GitHub_Git",
    "location": "GitHub_Git.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "GitHub_Search",
    "location": "GitHub_Search.html"
}, {
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}, {
    "name": "yourEvents",
    "location": "yourEvents.html"
}];

function Club_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'logout': 'Club_logout',
        'username': 'Club_username',
        'usernamelabel': 'Club_usernamelabel',
        'password': 'Club_password',
        'passwordlabel': 'Club_passwordlabel',
        'clubs': 'Club_clubs',
        'mobilegrid_30': 'Club_mobilegrid_30',
        'mobilegridcell_31': 'Club_mobilegridcell_31',
        'memberslabel': 'Club_memberslabel',
        'mobilenavbar_2': 'Club_mobilenavbar_2',
        'metab': 'Club_metab',
        'notify': 'Club_notify',
        'calendar': 'Club_calendar'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Club_logout_clone_1_onsuccess_mapping_0"] = {
        "homeScreen": "Club",
        "directions": []
    };

    Apperyio.mappings["Club_logout_clone_1_onbeforesend_mapping_0"] = {
        "homeScreen": "Club",
        "directions": [

        {
            "from_name": "userSessionToken",
            "from_type": "SESSION_STORAGE",

            "to_name": "logout_clone_1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['X-Appery-Session-Token']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Club_getmembers_onbeforesend_mapping_0"] = {
        "homeScreen": "Club",
        "directions": [

        {
            "from_name": "userID",
            "from_type": "SESSION_STORAGE",

            "to_name": "getmembers",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target_transformation": function(value) {
                    return '{"_id":"' + value + '"}';
                },
                "target": "$['parameters']['where']"

            }

            ]
        },

        {
            "from_name": "userSessionToken",
            "from_type": "SESSION_STORAGE",

            "to_name": "getmembers",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['X-Appery-Session-Token']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Club_getmembers_onsuccess_mapping_0"] = {
        "homeScreen": "Club",
        "directions": [

        {
            "from_name": "getmembers",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "members",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body'][0]['Members']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.logout_clone_1 = Apperyio.datasources.logout_clone_1 = new Apperyio.DataSource(UserInformation_logout_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Club_logout_clone_1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("Club");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Club_logout_clone_1_onsuccess_mapping_0"]);
            Apperyio.navigateTo('startScreen', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.getmembers = Apperyio.datasources.getmembers = new Apperyio.DataSource(UserInformation_UserType_query_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Club_getmembers_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("Club");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Club_getmembers_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'Club';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Club_onLoad = function() {
            Club_elementsExtraJS();

            try {
                $a.c15r("passwordlabel", "set", "text", $a.storage["password"].get("$"))
            } catch (e) {
                console.error(e)
            };
            try {
                $a.c15r("usernamelabel", "set", "text", $a.storage["username"].get("$"))
            } catch (e) {
                console.error(e)
            };
        	try {
                $a.c15r("clublabel", "set", "text", $a.storage["clubId"].get("$"))
            } catch (e) {
                console.error(e)
            };
            try {
                getmembers.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
            if (sessionStorage.getItem('members').length === 0) {
                sessionStorage.setItem('stringversion', "");
            } else sessionStorage.setItem('stringversion', sessionStorage.getItem('members').toString());
            try {
                $a.c15r("memberslabel", "set", "text", $a.storage["stringversion"].get("$"))
            } catch (e) {
                console.error(e)
            };

            Club_deviceEvents();
            Club_windowEvents();
            Club_elementsEvents();
        };

    // screen window events


    function Club_windowEvents() {

        $('#Club').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Club_deviceEvents() {
        document.addEventListener("deviceready", function() {

            $(document).bind("resume", function() {
                PushNotification.getPendingNotifications(function(status) {
                    var notifications = status.notifications;
                    for (var i = 0; i < notifications.length; ++i) {
                        PushNotification.notificationCallback(notifications[i]);
                    }
                });
            });

        });
    };

    // screen elements extra js


    function Club_elementsExtraJS() {
        // screen (Club) extra code

    };

    // screen elements handler


    function Club_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Club_mobileheader [name="logout"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        logout_clone_1.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#Club_mobileheader [name="logout"]');

        $(document).off("click", '#Club_mobilefooter [name="metab"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Club', {
                        reverse: false
                    });

                }
            },
        }, '#Club_mobilefooter [name="metab"]');
        $(document).off("click", '#Club_mobilefooter [name="notify"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    setTimeout(function() {
                        window.location = 'Notify.html';
                    }, 0);

                }
            },
        }, '#Club_mobilefooter [name="notify"]');
        $(document).off("click", '#Club_mobilefooter [name="calendar"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    setTimeout(function() {
                        window.location = 'Calendar.html';
                    }, 0);

                }
            },
        }, '#Club_mobilefooter [name="calendar"]');

    };

    $(document).off("pagebeforeshow", "#Club").on("pagebeforeshow", "#Club", function(event, ui) {
        Apperyio.CurrentScreen = "Club";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Club_onLoad();
};

$(document).off("pagecreate", "#Club").on("pagecreate", "#Club", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Club_js();
});