/*
 * JS for ExamplePage1426375367500 generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '96bf557e-32e1-4d20-ac3a-5655fb026817';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Club",
    "location": "Club.html"
}, {
    "name": "GitHub_Img",
    "location": "GitHub_Img.html"
}, {
    "name": "GitHub_File",
    "location": "GitHub_File.html"
}, {
    "name": "ExamplePage1426375367500",
    "location": "ExamplePage1426375367500.html"
}, {
    "name": "GitHub_Gist",
    "location": "GitHub_Gist.html"
}, {
    "name": "me",
    "location": "me.html"
}, {
    "name": "GitHub_Repo",
    "location": "GitHub_Repo.html"
}, {
    "name": "signIn",
    "location": "signIn.html"
}, {
    "name": "Notify",
    "location": "Notify.html"
}, {
    "name": "Calendar",
    "location": "Calendar.html"
}, {
    "name": "signUp",
    "location": "signUp.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "Notifications",
    "location": "Notifications.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "GitHub_Git",
    "location": "GitHub_Git.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "GitHub_Search",
    "location": "GitHub_Search.html"
}, {
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}, {
    "name": "yourEvents",
    "location": "yourEvents.html"
}];

function ExamplePage1426375367500_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'ExamplePage1426375367500_mobilebutton_2',
        'mobilebutton_3': 'ExamplePage1426375367500_mobilebutton_3',
        'mobiletextinput_4': 'ExamplePage1426375367500_mobiletextinput_4',
        'mobiledatepicker_5': 'ExamplePage1426375367500_mobiledatepicker_5',
        'mobilebutton_6': 'ExamplePage1426375367500_mobilebutton_6',
        'mobiletoggle_12': 'ExamplePage1426375367500_mobiletoggle_12',
        'mobileslider_11': 'ExamplePage1426375367500_mobileslider_11',
        'mobilelist_13': 'ExamplePage1426375367500_mobilelist_13',
        'mobilelistitem_14': 'ExamplePage1426375367500_mobilelistitem_14',
        'mobilelistitembutton_15': 'ExamplePage1426375367500_mobilelistitembutton_15',
        'mobilelistitem_16': 'ExamplePage1426375367500_mobilelistitem_16',
        'mobilelistitembutton_17': 'ExamplePage1426375367500_mobilelistitembutton_17',
        'mobilelistitem_18': 'ExamplePage1426375367500_mobilelistitem_18',
        'mobilelistitembutton_19': 'ExamplePage1426375367500_mobilelistitembutton_19',
        'mobilecheckboxgroup_7': 'ExamplePage1426375367500_mobilecheckboxgroup_7',
        'mobilecheckbox_8': 'ExamplePage1426375367500_mobilecheckbox_8',
        'mobilecheckbox_9': 'ExamplePage1426375367500_mobilecheckbox_9',
        'mobilenavbar_20': 'ExamplePage1426375367500_mobilenavbar_20',
        'mobilenavbaritem_21': 'ExamplePage1426375367500_mobilenavbaritem_21',
        'mobilenavbaritem_22': 'ExamplePage1426375367500_mobilenavbaritem_22',
        'mobilenavbaritem_23': 'ExamplePage1426375367500_mobilenavbaritem_23'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'ExamplePage1426375367500';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var ExamplePage1426375367500_onLoad = function() {
            ExamplePage1426375367500_elementsExtraJS();

            ExamplePage1426375367500_deviceEvents();
            ExamplePage1426375367500_windowEvents();
            ExamplePage1426375367500_elementsEvents();
        };

    // screen window events


    function ExamplePage1426375367500_windowEvents() {

        $('#ExamplePage1426375367500').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function ExamplePage1426375367500_deviceEvents() {
        document.addEventListener("deviceready", function() {

            $(document).bind("resume", function() {
                PushNotification.getPendingNotifications(function(status) {
                    var notifications = status.notifications;
                    for (var i = 0; i < notifications.length; ++i) {
                        PushNotification.notificationCallback(notifications[i]);
                    }
                });
            });

        });
    };

    // screen elements extra js


    function ExamplePage1426375367500_elementsExtraJS() {
        // screen (ExamplePage1426375367500) extra code

        /* mobiledatepicker_5 */

        ExamplePage1426375367500_mobiledatepicker_5_selector = "#ExamplePage1426375367500_mobiledatepicker_5";
        ExamplePage1426375367500_mobiledatepicker_5_dataPickerOptions = {
            dateFormat: "mm/dd/yy",
            firstDay: 0,

            maxDate: new Date(""),

            minDate: new Date(""),

            dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            showOtherMonths: true
        };

        ExamplePage1426375367500_mobiledatepicker_5_dataPickerOptions.defaultDate = new Date("10/21/2014");

        Apperyio.__registerComponent('mobiledatepicker_5', new Apperyio.ApperyMobileDatePickerComponent("ExamplePage1426375367500_mobiledatepicker_5", ExamplePage1426375367500_mobiledatepicker_5_dataPickerOptions));

        /* mobiletoggle_12 */

        $("#ExamplePage1426375367500_mobiletoggle_12").parent().find(".ui-flipswitch-on").attr("tabindex", "8");

        /* mobilelist_13 */

        listView = $("#ExamplePage1426375367500_mobilelist_13");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#ExamplePage1426375367500_mobilelist_13 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_14 */

        /* mobilelistitem_16 */

        /* mobilelistitem_18 */

    };

    // screen elements handler


    function ExamplePage1426375367500_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#ExamplePage1426375367500").on("pagebeforeshow", "#ExamplePage1426375367500", function(event, ui) {
        Apperyio.CurrentScreen = "ExamplePage1426375367500";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    ExamplePage1426375367500_onLoad();
};

$(document).off("pagecreate", "#ExamplePage1426375367500").on("pagecreate", "#ExamplePage1426375367500", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    ExamplePage1426375367500_js();
});