/*
 * JS for GitHub_Gist generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '96bf557e-32e1-4d20-ac3a-5655fb026817';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Club",
    "location": "Club.html"
}, {
    "name": "GitHub_Img",
    "location": "GitHub_Img.html"
}, {
    "name": "GitHub_File",
    "location": "GitHub_File.html"
}, {
    "name": "ExamplePage1426375367500",
    "location": "ExamplePage1426375367500.html"
}, {
    "name": "GitHub_Gist",
    "location": "GitHub_Gist.html"
}, {
    "name": "me",
    "location": "me.html"
}, {
    "name": "GitHub_Repo",
    "location": "GitHub_Repo.html"
}, {
    "name": "signIn",
    "location": "signIn.html"
}, {
    "name": "Notify",
    "location": "Notify.html"
}, {
    "name": "Calendar",
    "location": "Calendar.html"
}, {
    "name": "signUp",
    "location": "signUp.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "Notifications",
    "location": "Notifications.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "GitHub_Git",
    "location": "GitHub_Git.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "GitHub_Search",
    "location": "GitHub_Search.html"
}, {
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}, {
    "name": "yourEvents",
    "location": "yourEvents.html"
}];

function GitHub_Gist_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'gistDescription': 'GitHub_Gist_gistDescription',
        'gistPanel': 'GitHub_Gist_gistPanel',
        'gistCommentGrid': 'GitHub_Gist_gistCommentGrid',
        'mobilegridcell_13': 'GitHub_Gist_mobilegridcell_13',
        'gistCommentAva': 'GitHub_Gist_gistCommentAva',
        'mobilegridcell_14': 'GitHub_Gist_mobilegridcell_14',
        'commentUserLogin': 'GitHub_Gist_commentUserLogin',
        'commentContent': 'GitHub_Gist_commentContent'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["GitHub_Gist_getGistServ_onbeforesend_mapping_0"] = {
        "homeScreen": "GitHub_Gist",
        "directions": [

        {
            "from_name": "currentGistId",
            "from_type": "LOCAL_STORAGE",

            "to_name": "getGistServ",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['id']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["GitHub_Gist_getGistServ_onsuccess_mapping_0"] = {
        "homeScreen": "GitHub_Gist",
        "directions": []
    };

    Apperyio.mappings["GitHub_Gist_getGistCommentsServ_onbeforesend_mapping_0"] = {
        "homeScreen": "GitHub_Gist",
        "directions": [

        {
            "from_name": "currentGistId",
            "from_type": "LOCAL_STORAGE",

            "to_name": "getGistCommentsServ",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['gist_id']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["GitHub_Gist_getGistCommentsServ_onsuccess_mapping_0"] = {
        "homeScreen": "GitHub_Gist",
        "directions": [

        {
            "from_name": "getGistCommentsServ",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "GitHub_Gist",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body'][i]",
                "target": "$['gistCommentGrid']"

            },

            {

                "source": "$['body'][i]['user']['login']",
                "target": "$['gistCommentGrid']['commentUserLogin:text']"

            },

            {

                "source": "$['body'][i]['body']",
                "target": "$['gistCommentGrid']['commentContent:text']"

            },

            {

                "source": "$['body'][i]['user']['avatar_url']",
                "target": "$['gistCommentGrid']['gistCommentAva:image']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.getGistServ = Apperyio.datasources.getGistServ = new Apperyio.DataSource(GitHub_getGist, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Gist_getGistServ_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            try {
                getGistCommentsServ.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

            Apperyio.refreshScreenFormElements("GitHub_Gist");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Gist_getGistServ_onsuccess_mapping_0"]);
            Appery('gistPanel').html(Helpers.fillGist(data.files));
            Appery('gistDescription').text(data.description);
            Appery('gistPanel').find('pre code').each(function(i, e) {
                hljs.highlightBlock(e)
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.getGistCommentsServ = Apperyio.datasources.getGistCommentsServ = new Apperyio.DataSource(GitHub_getGistComments, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Gist_getGistCommentsServ_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("GitHub_Gist");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Gist_getGistCommentsServ_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'GitHub_Gist';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var GitHub_Gist_onLoad = function() {
            GitHub_Gist_elementsExtraJS();

            GitHub_Gist_deviceEvents();
            GitHub_Gist_windowEvents();
            GitHub_Gist_elementsEvents();
        };

    // screen window events


    function GitHub_Gist_windowEvents() {

        $('#GitHub_Gist').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#GitHub_Gist').on({
            pageshow: function(event) {
                try {
                    getGistServ.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
            },
        });

    };

    // device events


    function GitHub_Gist_deviceEvents() {
        document.addEventListener("deviceready", function() {

            $(document).bind("resume", function() {
                PushNotification.getPendingNotifications(function(status) {
                    var notifications = status.notifications;
                    for (var i = 0; i < notifications.length; ++i) {
                        PushNotification.notificationCallback(notifications[i]);
                    }
                });
            });

        });
    };

    // screen elements extra js


    function GitHub_Gist_elementsExtraJS() {
        // screen (GitHub_Gist) extra code

    };

    // screen elements handler


    function GitHub_Gist_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#GitHub_Gist").on("pagebeforeshow", "#GitHub_Gist", function(event, ui) {
        Apperyio.CurrentScreen = "GitHub_Gist";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    GitHub_Gist_onLoad();
};

$(document).off("pagecreate", "#GitHub_Gist").on("pagecreate", "#GitHub_Gist", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    GitHub_Gist_js();
});