/*
 * JS for GitHub_File generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '96bf557e-32e1-4d20-ac3a-5655fb026817';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Club",
    "location": "Club.html"
}, {
    "name": "GitHub_Img",
    "location": "GitHub_Img.html"
}, {
    "name": "GitHub_File",
    "location": "GitHub_File.html"
}, {
    "name": "ExamplePage1426375367500",
    "location": "ExamplePage1426375367500.html"
}, {
    "name": "GitHub_Gist",
    "location": "GitHub_Gist.html"
}, {
    "name": "me",
    "location": "me.html"
}, {
    "name": "GitHub_Repo",
    "location": "GitHub_Repo.html"
}, {
    "name": "signIn",
    "location": "signIn.html"
}, {
    "name": "Notify",
    "location": "Notify.html"
}, {
    "name": "Calendar",
    "location": "Calendar.html"
}, {
    "name": "signUp",
    "location": "signUp.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "Notifications",
    "location": "Notifications.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "GitHub_Git",
    "location": "GitHub_Git.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "GitHub_Search",
    "location": "GitHub_Search.html"
}, {
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}, {
    "name": "yourEvents",
    "location": "yourEvents.html"
}];

function GitHub_File_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'filePanel': 'GitHub_File_filePanel'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["GitHub_File_getBlobServ_onbeforesend_mapping_0"] = {
        "homeScreen": "GitHub_File",
        "directions": [

        {
            "from_name": "currentRepo",
            "from_type": "LOCAL_STORAGE",

            "to_name": "getBlobServ",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['repo_id']"

            }

            ]
        },

        {
            "from_name": "currentSHA",
            "from_type": "LOCAL_STORAGE",

            "to_name": "getBlobServ",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sha']"

            }

            ]
        },

        {
            "from_name": "currentUserLogin",
            "from_type": "LOCAL_STORAGE",

            "to_name": "getBlobServ",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['user_login']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["GitHub_File_getBlobServ_onsuccess_mapping_0"] = {
        "homeScreen": "GitHub_File",
        "directions": []
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.getBlobServ = Apperyio.datasources.getBlobServ = new Apperyio.DataSource(GitHub_getBlob, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_File_getBlobServ_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("GitHub_File");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_File_getBlobServ_onsuccess_mapping_0"]);
            Appery('filePanel').html(Helpers.getFileContent(data.content));
            Appery('filePanel').find('pre code').each(function(i, e) {
                hljs.highlightBlock(e)
            });
            Appery('filePanel').scrollTop(0);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'GitHub_File';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var GitHub_File_onLoad = function() {
            GitHub_File_elementsExtraJS();

            GitHub_File_deviceEvents();
            GitHub_File_windowEvents();
            GitHub_File_elementsEvents();
        };

    // screen window events


    function GitHub_File_windowEvents() {

        $('#GitHub_File').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#GitHub_File').on({
            pageshow: function(event) {
                Appery("fileHeader").text(localStorage.getItem("currentFileName"));
                Helpers.resizeTextArea();
                $(window).bind("resize", Helpers.resizeTextArea);
                try {
                    getBlobServ.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
            },
            pagehide: function(event) {
                $(window).unbind("resize", Helpers.resizeTextArea);
            },
        });

    };

    // device events


    function GitHub_File_deviceEvents() {
        document.addEventListener("deviceready", function() {

            $(document).bind("resume", function() {
                PushNotification.getPendingNotifications(function(status) {
                    var notifications = status.notifications;
                    for (var i = 0; i < notifications.length; ++i) {
                        PushNotification.notificationCallback(notifications[i]);
                    }
                });
            });

        });
    };

    // screen elements extra js


    function GitHub_File_elementsExtraJS() {
        // screen (GitHub_File) extra code

    };

    // screen elements handler


    function GitHub_File_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#GitHub_File").on("pagebeforeshow", "#GitHub_File", function(event, ui) {
        Apperyio.CurrentScreen = "GitHub_File";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    GitHub_File_onLoad();
};

$(document).off("pagecreate", "#GitHub_File").on("pagecreate", "#GitHub_File", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    GitHub_File_js();
});