/*
 * JS for GitHub_Img generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '96bf557e-32e1-4d20-ac3a-5655fb026817';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Club",
    "location": "Club.html"
}, {
    "name": "GitHub_Img",
    "location": "GitHub_Img.html"
}, {
    "name": "GitHub_File",
    "location": "GitHub_File.html"
}, {
    "name": "ExamplePage1426375367500",
    "location": "ExamplePage1426375367500.html"
}, {
    "name": "GitHub_Gist",
    "location": "GitHub_Gist.html"
}, {
    "name": "me",
    "location": "me.html"
}, {
    "name": "GitHub_Repo",
    "location": "GitHub_Repo.html"
}, {
    "name": "signIn",
    "location": "signIn.html"
}, {
    "name": "Notify",
    "location": "Notify.html"
}, {
    "name": "Calendar",
    "location": "Calendar.html"
}, {
    "name": "signUp",
    "location": "signUp.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "Notifications",
    "location": "Notifications.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "GitHub_Git",
    "location": "GitHub_Git.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "GitHub_Search",
    "location": "GitHub_Search.html"
}, {
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}, {
    "name": "yourEvents",
    "location": "yourEvents.html"
}];

function GitHub_Img_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'imgFile': 'GitHub_Img_imgFile'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["GitHub_Img_getImgServ_onbeforesend_mapping_0"] = {
        "homeScreen": "GitHub_Img",
        "directions": [

        {

            "to_name": "getImgServ",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["GitHub_Img_getImgServ_onsuccess_mapping_0"] = {
        "homeScreen": "GitHub_Img",
        "directions": [

        {
            "from_name": "getImgServ",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "GitHub_Img",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['content']",
                "target_transformation": function(value, element) {
                    return "data:image/jpg;base64," + Helpers.removeHiddenChars(value);
                },
                "target": "$['imgFile:image']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.getImgServ = Apperyio.datasources.getImgServ = new Apperyio.DataSource(GitHub_getBlob, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Img_getImgServ_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("GitHub_Img");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Img_getImgServ_onsuccess_mapping_0"]);
            toggle('GitHub_Img_imgFile', 'mob', 'true');
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'GitHub_Img';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var GitHub_Img_onLoad = function() {
            GitHub_Img_elementsExtraJS();

            GitHub_Img_deviceEvents();
            GitHub_Img_windowEvents();
            GitHub_Img_elementsEvents();
        };

    // screen window events


    function GitHub_Img_windowEvents() {

        $('#GitHub_Img').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#GitHub_Img').on({
            pageshow: function(event) {
                Appery("imgHeader").text(localStorage.getItem("currentFileName"));
                try {
                    getImgServ.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
            },
        });

    };

    // device events


    function GitHub_Img_deviceEvents() {
        document.addEventListener("deviceready", function() {

            $(document).bind("resume", function() {
                PushNotification.getPendingNotifications(function(status) {
                    var notifications = status.notifications;
                    for (var i = 0; i < notifications.length; ++i) {
                        PushNotification.notificationCallback(notifications[i]);
                    }
                });
            });

        });
    };

    // screen elements extra js


    function GitHub_Img_elementsExtraJS() {
        // screen (GitHub_Img) extra code

    };

    // screen elements handler


    function GitHub_Img_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#GitHub_Img").on("pagebeforeshow", "#GitHub_Img", function(event, ui) {
        Apperyio.CurrentScreen = "GitHub_Img";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    GitHub_Img_onLoad();
};

$(document).off("pagecreate", "#GitHub_Img").on("pagecreate", "#GitHub_Img", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    GitHub_Img_js();
});