/*
 * JS for GitHub_Search generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '96bf557e-32e1-4d20-ac3a-5655fb026817';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Club",
    "location": "Club.html"
}, {
    "name": "GitHub_Img",
    "location": "GitHub_Img.html"
}, {
    "name": "GitHub_File",
    "location": "GitHub_File.html"
}, {
    "name": "ExamplePage1426375367500",
    "location": "ExamplePage1426375367500.html"
}, {
    "name": "GitHub_Gist",
    "location": "GitHub_Gist.html"
}, {
    "name": "me",
    "location": "me.html"
}, {
    "name": "GitHub_Repo",
    "location": "GitHub_Repo.html"
}, {
    "name": "signIn",
    "location": "signIn.html"
}, {
    "name": "Notify",
    "location": "Notify.html"
}, {
    "name": "Calendar",
    "location": "Calendar.html"
}, {
    "name": "signUp",
    "location": "signUp.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "Notifications",
    "location": "Notifications.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "GitHub_Git",
    "location": "GitHub_Git.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "GitHub_Search",
    "location": "GitHub_Search.html"
}, {
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}, {
    "name": "yourEvents",
    "location": "yourEvents.html"
}];

function GitHub_Search_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'searchNavBar': 'GitHub_Search_searchNavBar',
        'usersTab': 'GitHub_Search_usersTab',
        'reposTab': 'GitHub_Search_reposTab',
        'gistsTab': 'GitHub_Search_gistsTab',
        'logoutButton': 'GitHub_Search_logoutButton',
        'myGitButton': 'GitHub_Search_myGitButton',
        'authorizeButton': 'GitHub_Search_authorizeButton',
        'usersGrid': 'GitHub_Search_usersGrid',
        'mobilegridcell_34': 'GitHub_Search_mobilegridcell_34',
        'userSearch': 'GitHub_Search_userSearch',
        'mobilegridcell_38': 'GitHub_Search_mobilegridcell_38',
        'usersRes': 'GitHub_Search_usersRes',
        'mobilegridcell_42': 'GitHub_Search_mobilegridcell_42',
        'avaImg': 'GitHub_Search_avaImg',
        'mobilegridcell_43': 'GitHub_Search_mobilegridcell_43',
        'login': 'GitHub_Search_login',
        'repoGrid': 'GitHub_Search_repoGrid',
        'mobilegridcell_51': 'GitHub_Search_mobilegridcell_51',
        'repoSearch': 'GitHub_Search_repoSearch',
        'mobilegridcell_53': 'GitHub_Search_mobilegridcell_53',
        'searchRepoGrid': 'GitHub_Search_searchRepoGrid',
        'mobilegridcell_57': 'GitHub_Search_mobilegridcell_57',
        'mobilelabel1_84': 'GitHub_Search_mobilelabel1_84',
        'mobilegridcell_82': 'GitHub_Search_mobilegridcell_82',
        'repoTitle': 'GitHub_Search_repoTitle',
        'repoUserLogin': 'GitHub_Search_repoUserLogin',
        'repoDescription': 'GitHub_Search_repoDescription',
        'gistsGrid': 'GitHub_Search_gistsGrid',
        'mobilegridcell_64': 'GitHub_Search_mobilegridcell_64',
        'searchUserGists': 'GitHub_Search_searchUserGists',
        'mobilegridcell_66': 'GitHub_Search_mobilegridcell_66',
        'searchResGistsGrid': 'GitHub_Search_searchResGistsGrid',
        'mobilegridcell_70': 'GitHub_Search_mobilegridcell_70',
        'searchGistsAva': 'GitHub_Search_searchGistsAva',
        'gistId': 'GitHub_Search_gistId',
        'mobilegridcell_81': 'GitHub_Search_mobilegridcell_81',
        'searchGistDescr': 'GitHub_Search_searchGistDescr',
        'gistUserLogin': 'GitHub_Search_gistUserLogin'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["GitHub_Search_getUsersServ_onbeforesend_mapping_0"] = {
        "homeScreen": "GitHub_Search",
        "directions": [

        {

            "to_name": "getUsersServ",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["GitHub_Search_getUsersServ_onsuccess_mapping_0"] = {
        "homeScreen": "GitHub_Search",
        "directions": [

        {
            "from_name": "getUsersServ",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "GitHub_Search",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body'][i]",
                "target": "$['usersRes']"

            },

            {

                "source": "$['body'][i]['avatar_url']",
                "target": "$['usersRes']['avaImg:image']"

            },

            {

                "source": "$['body'][i]['login']",
                "target": "$['usersRes']['login:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["GitHub_Search_searchUsersServ_onbeforesend_mapping_0"] = {
        "homeScreen": "GitHub_Search",
        "directions": [

        {
            "from_name": "GitHub_Search",
            "from_type": "UI",

            "to_name": "searchUsersServ",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['userSearch:text']",
                "target_transformation": function(value) {
                    return (value != "") ? value : "";
                },
                "target": "$['parameters']['keyword']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["GitHub_Search_searchUsersServ_onsuccess_mapping_0"] = {
        "homeScreen": "GitHub_Search",
        "directions": []
    };

    Apperyio.mappings["GitHub_Search_searchReposServ_onbeforesend_mapping_0"] = {
        "homeScreen": "GitHub_Search",
        "directions": [

        {
            "from_name": "GitHub_Search",
            "from_type": "UI",

            "to_name": "searchReposServ",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['repoSearch:text']",
                "target_transformation": function(value) {
                    return (value != "") ? value : "";
                },
                "target": "$['parameters']['keyword']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["GitHub_Search_searchReposServ_onsuccess_mapping_0"] = {
        "homeScreen": "GitHub_Search",
        "directions": [

        {
            "from_name": "searchReposServ",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "GitHub_Search",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['repositories'][i]['description']",
                "target": "$['searchRepoGrid']['repoDescription:text']"

            },

            {

                "source": "$['body']['repositories'][i]['username']",
                "target": "$['searchRepoGrid']['repoUserLogin:text']"

            },

            {

                "source": "$['body']['repositories'][i]['name']",
                "target": "$['searchRepoGrid']['repoTitle:text']"

            },

            {

                "source": "$['body']['repositories'][i]",
                "target": "$['searchRepoGrid']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["GitHub_Search_getReposServ_onbeforesend_mapping_0"] = {
        "homeScreen": "GitHub_Search",
        "directions": [

        {

            "to_name": "getReposServ",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["GitHub_Search_getReposServ_onsuccess_mapping_0"] = {
        "homeScreen": "GitHub_Search",
        "directions": [

        {
            "from_name": "getReposServ",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "GitHub_Search",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body'][i]['owner']['login']",
                "target": "$['searchRepoGrid']['repoUserLogin:text']"

            },

            {

                "source": "$['body'][i]",
                "target": "$['searchRepoGrid']"

            },

            {

                "source": "$['body'][i]['description']",
                "target": "$['searchRepoGrid']['repoDescription:text']"

            },

            {

                "source": "$['body'][i]['name']",
                "target": "$['searchRepoGrid']['repoTitle:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["GitHub_Search_getPublicGistsServ_onbeforesend_mapping_0"] = {
        "homeScreen": "GitHub_Search",
        "directions": [

        {
            "from_name": "access_token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "getPublicGistsServ",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "params": "public"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['access_token']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["GitHub_Search_getPublicGistsServ_onsuccess_mapping_0"] = {
        "homeScreen": "GitHub_Search",
        "directions": [

        {
            "from_name": "getPublicGistsServ",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "GitHub_Search",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body'][i]",
                "target": "$['searchResGistsGrid']"

            },

            {

                "source": "$['body'][i]['user']['avatar_url']",
                "target": "$['searchResGistsGrid']['searchGistsAva:image']"

            },

            {

                "source": "$['body'][i]['user']['login']",
                "target": "$['searchResGistsGrid']['gistUserLogin:text']"

            },

            {

                "source": "$['body'][i]['description']",
                "target_transformation": function(value, element) {
                    return (value == "") ? "No description" : value;
                },
                "target": "$['searchResGistsGrid']['searchGistDescr:text']"

            },

            {

                "source": "$['body'][i]['id']",
                "target": "$['searchResGistsGrid']['gistId:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["GitHub_Search_getAccessTokenServ_onbeforesend_mapping_0"] = {
        "homeScreen": "GitHub_Search",
        "directions": [

        {

            "to_name": "getAccessTokenServ",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Accept": "application/json",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "client_id": "{client_id}",
                    "client_secret": "{client_secret}"
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["GitHub_Search_getAccessTokenServ_onsuccess_mapping_0"] = {
        "homeScreen": "GitHub_Search",
        "directions": [

        {
            "from_name": "getAccessTokenServ",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "access_token",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['access_token']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["GitHub_Search_getUserGistsServ_onbeforesend_mapping_0"] = {
        "homeScreen": "GitHub_Search",
        "directions": [

        {
            "from_name": "GitHub_Search",
            "from_type": "UI",

            "to_name": "getUserGistsServ",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['searchUserGists:text']",
                "target": "$['parameters']['user']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["GitHub_Search_getUserGistsServ_onsuccess_mapping_0"] = {
        "homeScreen": "GitHub_Search",
        "directions": [

        {
            "from_name": "getUserGistsServ",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "GitHub_Search",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body'][i]['user']['login']",
                "target": "$['searchResGistsGrid']['gistUserLogin:text']"

            },

            {

                "source": "$['body'][i]['description']",
                "target_transformation": function(value, element) {
                    return (value == "") ? "No description" : value;
                },
                "target": "$['searchResGistsGrid']['searchGistDescr:text']"

            },

            {

                "source": "$['body'][i]",
                "target": "$['searchResGistsGrid']"

            },

            {

                "source": "$['body'][i]['id']",
                "target": "$['searchResGistsGrid']['gistId:text']"

            },

            {

                "source": "$['body'][i]['user']['avatar_url']",
                "target": "$['searchResGistsGrid']['searchGistsAva:image']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.getUsersServ = Apperyio.datasources.getUsersServ = new Apperyio.DataSource(GitHub_getUsers, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Search_getUsersServ_onbeforesend_mapping_0"]);
            $('.GitHub_Search_usersGrid_wrapper').show();
            $('.GitHub_Search_repoGrid_wrapper').hide();
            $('.GitHub_Search_gistsGrid_wrapper').hide();
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("GitHub_Search");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Search_getUsersServ_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.searchUsersServ = Apperyio.datasources.searchUsersServ = new Apperyio.DataSource(GitHub_searchUsers, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Search_searchUsersServ_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("GitHub_Search");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Search_searchUsersServ_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.searchReposServ = Apperyio.datasources.searchReposServ = new Apperyio.DataSource(GitHub_searchRepos, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Search_searchReposServ_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("GitHub_Search");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Search_searchReposServ_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.getReposServ = Apperyio.datasources.getReposServ = new Apperyio.DataSource(GitHub_getRepos, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Search_getReposServ_onbeforesend_mapping_0"]);
            $('.GitHub_Search_usersGrid_wrapper').hide();
            $('.GitHub_Search_repoGrid_wrapper').show();
            $('.GitHub_Search_gistsGrid_wrapper').hide();
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("GitHub_Search");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Search_getReposServ_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.getPublicGistsServ = Apperyio.datasources.getPublicGistsServ = new Apperyio.DataSource(GitHub_searchGists, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Search_getPublicGistsServ_onbeforesend_mapping_0"]);
            $('.GitHub_Search_usersGrid_wrapper').hide();
            $('.GitHub_Search_repoGrid_wrapper').hide();
            $('.GitHub_Search_gistsGrid_wrapper').show();
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("GitHub_Search");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Search_getPublicGistsServ_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.getAccessTokenServ = Apperyio.datasources.getAccessTokenServ = new Apperyio.DataSource(GitHub_getAccessToken, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Search_getAccessTokenServ_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("GitHub_Search");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Search_getAccessTokenServ_onsuccess_mapping_0"]);
            if (data.error) {
                Helpers.authorize();
            } else {
                Helpers.searchPageInit();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            Helpers.authorize();
        }
    });

    window.getUserGistsServ = Apperyio.datasources.getUserGistsServ = new Apperyio.DataSource(GitHub_getUserGists, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Search_getUserGistsServ_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("GitHub_Search");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["GitHub_Search_getUserGistsServ_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'GitHub_Search';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var GitHub_Search_onLoad = function() {
            GitHub_Search_elementsExtraJS();

            Helpers.initNavBar();

            GitHub_Search_deviceEvents();
            GitHub_Search_windowEvents();
            GitHub_Search_elementsEvents();
        };

    // screen window events


    function GitHub_Search_windowEvents() {

        $('#GitHub_Search').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#GitHub_Search').on({
            pageshow: function(event) {
                Helpers.searchPageShowHandler();
            },
            pagehide: function(event) {
                Helpers.searchPageHideHandler();
            },
        });

    };

    // device events


    function GitHub_Search_deviceEvents() {
        document.addEventListener("deviceready", function() {

            $(document).bind("resume", function() {
                PushNotification.getPendingNotifications(function(status) {
                    var notifications = status.notifications;
                    for (var i = 0; i < notifications.length; ++i) {
                        PushNotification.notificationCallback(notifications[i]);
                    }
                });
            });

        });
    };

    // screen elements extra js


    function GitHub_Search_elementsExtraJS() {
        // screen (GitHub_Search) extra code

    };

    // screen elements handler


    function GitHub_Search_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#GitHub_Search_searchHeader [name="usersTab"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $(".searchGrid").hide();
                    toggle('GitHub_Search_usersGrid', 'mob', 'true');
                    try {
                        getUsersServ.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#GitHub_Search_searchHeader [name="usersTab"]');
        $(document).off("click", '#GitHub_Search_searchHeader [name="reposTab"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $(".searchGrid").hide();
                    toggle('GitHub_Search_repoGrid', 'mob', 'true');
                    try {
                        getReposServ.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#GitHub_Search_searchHeader [name="reposTab"]');
        $(document).off("click", '#GitHub_Search_searchHeader [name="gistsTab"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $(".searchGrid").hide();
                    toggle('GitHub_Search_gistsGrid', 'mob', 'true');
                    try {
                        getPublicGistsServ.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#GitHub_Search_searchHeader [name="gistsTab"]');
        $(document).off("click", '#GitHub_Search_searchHeader [name="logoutButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Helpers.logout();

                }
            },
        }, '#GitHub_Search_searchHeader [name="logoutButton"]');
        $(document).off("click", '#GitHub_Search_searchHeader [name="myGitButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var access_token = localStorage.getItem("access_token");
                    if (access_token) {
                        Appery.navigateTo("GitHub_Git");
                    };

                }
            },
        }, '#GitHub_Search_searchHeader [name="myGitButton"]');

        $(document).off("click", '#GitHub_Search_mobilecontainer1 [name="authorizeButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Helpers.authorize();

                }
            },
        }, '#GitHub_Search_mobilecontainer1 [name="authorizeButton"]');

        $(document).off("vclick", "#GitHub_Search_userSearch-cover-img").on({
            vclick: function(event) {
                if (!$(this).attr('disabled')) {
                    Helpers.searchFix("user", Appery("userSearch").val());
                }
            }
        }, "#GitHub_Search_userSearch-cover-img");

        $(document).off("vclick", "#GitHub_Search_repoSearch-cover-img").on({
            vclick: function(event) {
                if (!$(this).attr('disabled')) {
                    Helpers.searchFix("repo", Appery("repoSearch").val());
                }
            }
        }, "#GitHub_Search_repoSearch-cover-img");

        $(document).off("vclick", '#GitHub_Search_mobilecontainer1 [name="searchRepoGrid"]').on({
            vclick: function(event) {
                Helpers.folderStack.length = 0;
                localStorage.currentRepo = $.trim($(this).find('[name="repoTitle"]').text());
                localStorage.currentUserLogin = $.trim($(this).find('[name="repoUserLogin"]').text());
                Apperyio.navigateTo('GitHub_Repo', {
                    transition: 'slide',
                    reverse: false
                });
            },
        }, '#GitHub_Search_mobilecontainer1 [name="searchRepoGrid"]');

        $(document).off("vclick", "#GitHub_Search_searchUserGists-cover-img").on({
            vclick: function(event) {
                if (!$(this).attr('disabled')) {
                    Helpers.searchFix("gist", Appery("searchUserGists").val());
                }
            }
        }, "#GitHub_Search_searchUserGists-cover-img");

        $(document).off("vclick click", '#GitHub_Search_mobilecontainer1 [name="searchResGistsGrid"]').on({
            vclick: function(event) {
                Apperyio.navigateTo('GitHub_Gist', {
                    transition: 'slide',
                    reverse: false
                });
            },
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    localStorage.currentGistId = $.trim($(this).find('[name="gistId"]').text());

                }
            },
        }, '#GitHub_Search_mobilecontainer1 [name="searchResGistsGrid"]');

    };

    $(document).off("pagebeforeshow", "#GitHub_Search").on("pagebeforeshow", "#GitHub_Search", function(event, ui) {
        Apperyio.CurrentScreen = "GitHub_Search";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    GitHub_Search_onLoad();
};

$(document).off("pagecreate", "#GitHub_Search").on("pagecreate", "#GitHub_Search", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    GitHub_Search_js();
});