/*
 * JS for MaterialDesignPage generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '96bf557e-32e1-4d20-ac3a-5655fb026817';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Club",
    "location": "Club.html"
}, {
    "name": "GitHub_Img",
    "location": "GitHub_Img.html"
}, {
    "name": "GitHub_File",
    "location": "GitHub_File.html"
}, {
    "name": "ExamplePage1426375367500",
    "location": "ExamplePage1426375367500.html"
}, {
    "name": "GitHub_Gist",
    "location": "GitHub_Gist.html"
}, {
    "name": "me",
    "location": "me.html"
}, {
    "name": "GitHub_Repo",
    "location": "GitHub_Repo.html"
}, {
    "name": "signIn",
    "location": "signIn.html"
}, {
    "name": "Notify",
    "location": "Notify.html"
}, {
    "name": "Calendar",
    "location": "Calendar.html"
}, {
    "name": "signUp",
    "location": "signUp.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "Notifications",
    "location": "Notifications.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "GitHub_Git",
    "location": "GitHub_Git.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "GitHub_Search",
    "location": "GitHub_Search.html"
}, {
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}, {
    "name": "yourEvents",
    "location": "yourEvents.html"
}];

function MaterialDesignPage_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobiletextinput_2': 'MaterialDesignPage_mobiletextinput_2',
        'mobilebutton_3': 'MaterialDesignPage_mobilebutton_3',
        'mobilelist_4': 'MaterialDesignPage_mobilelist_4',
        'mobilelistitem_5': 'MaterialDesignPage_mobilelistitem_5',
        'mobilelistitembutton_6': 'MaterialDesignPage_mobilelistitembutton_6',
        'mobilelistitem_7': 'MaterialDesignPage_mobilelistitem_7',
        'mobilelistitembutton_8': 'MaterialDesignPage_mobilelistitembutton_8',
        'mobileradiogroup_17': 'MaterialDesignPage_mobileradiogroup_17',
        'mobileradiobutton_18': 'MaterialDesignPage_mobileradiobutton_18',
        'mobileradiobutton_19': 'MaterialDesignPage_mobileradiobutton_19',
        'mobileselectmenu_11': 'MaterialDesignPage_mobileselectmenu_11',
        'mobileselectmenu_11-0': 'MaterialDesignPage_mobileselectmenu_11-0',
        'mobilecollapsblock_14': 'MaterialDesignPage_mobilecollapsblock_14',
        'mobilecollapsblockheader_15': 'MaterialDesignPage_mobilecollapsblockheader_15',
        'mobilecollapsblockcontent_16': 'MaterialDesignPage_mobilecollapsblockcontent_16'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'MaterialDesignPage';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var MaterialDesignPage_onLoad = function() {
            MaterialDesignPage_elementsExtraJS();

            MaterialDesignPage_deviceEvents();
            MaterialDesignPage_windowEvents();
            MaterialDesignPage_elementsEvents();
        };

    // screen window events


    function MaterialDesignPage_windowEvents() {

        $('#MaterialDesignPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function MaterialDesignPage_deviceEvents() {
        document.addEventListener("deviceready", function() {

            $(document).bind("resume", function() {
                PushNotification.getPendingNotifications(function(status) {
                    var notifications = status.notifications;
                    for (var i = 0; i < notifications.length; ++i) {
                        PushNotification.notificationCallback(notifications[i]);
                    }
                });
            });

        });
    };

    // screen elements extra js


    function MaterialDesignPage_elementsExtraJS() {
        // screen (MaterialDesignPage) extra code

        /* mobilelist_4 */

        listView = $("#MaterialDesignPage_mobilelist_4");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#MaterialDesignPage_mobilelist_4 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_5 */

        /* mobilelistitem_7 */

        /* mobileselectmenu_11 */

        $("#MaterialDesignPage_mobileselectmenu_11").parent().find("a.ui-btn").attr("tabindex", "4");

        /* mobilecollapsblock_14 */

        $("#MaterialDesignPage_mobilecollapsblock_14 .ui-collapsible-heading-toggle").attr("tabindex", "6");

    };

    // screen elements handler


    function MaterialDesignPage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#MaterialDesignPage").on("pagebeforeshow", "#MaterialDesignPage", function(event, ui) {
        Apperyio.CurrentScreen = "MaterialDesignPage";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    MaterialDesignPage_onLoad();
};

$(document).off("pagecreate", "#MaterialDesignPage").on("pagecreate", "#MaterialDesignPage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    MaterialDesignPage_js();
});