/*
 * JS for me generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '96bf557e-32e1-4d20-ac3a-5655fb026817';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Club",
    "location": "Club.html"
}, {
    "name": "GitHub_Img",
    "location": "GitHub_Img.html"
}, {
    "name": "GitHub_File",
    "location": "GitHub_File.html"
}, {
    "name": "ExamplePage1426375367500",
    "location": "ExamplePage1426375367500.html"
}, {
    "name": "GitHub_Gist",
    "location": "GitHub_Gist.html"
}, {
    "name": "me",
    "location": "me.html"
}, {
    "name": "GitHub_Repo",
    "location": "GitHub_Repo.html"
}, {
    "name": "signIn",
    "location": "signIn.html"
}, {
    "name": "Notify",
    "location": "Notify.html"
}, {
    "name": "Calendar",
    "location": "Calendar.html"
}, {
    "name": "signUp",
    "location": "signUp.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "Notifications",
    "location": "Notifications.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "GitHub_Git",
    "location": "GitHub_Git.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "GitHub_Search",
    "location": "GitHub_Search.html"
}, {
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}, {
    "name": "yourEvents",
    "location": "yourEvents.html"
}];

function me_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'logout': 'me_logout',
        'addclub': 'me_addclub',
        'username': 'me_username',
        'usernamelabel': 'me_usernamelabel',
        'password': 'me_password',
        'passwordlabel': 'me_passwordlabel',
        'clubs': 'me_clubs',
        'mobilegrid_37': 'me_mobilegrid_37',
        'mobilegridcell_38': 'me_mobilegridcell_38',
        'clubslabel': 'me_clubslabel',
        'mobilenavbar_2': 'me_mobilenavbar_2',
        'metab': 'me_metab',
        'notify': 'me_notify',
        'calendar': 'me_calendar',
        'clubnameinput': 'me_clubnameinput',
        'searchbutton': 'me_searchbutton',
        'mobilegrid_18': 'me_mobilegrid_18',
        'mobilegridcell_19': 'me_mobilegridcell_19',
        'clubname': 'me_clubname',
        'mobilegridcell_24': 'me_mobilegridcell_24',
        'administrator': 'me_administrator',
        'mobilegridcell_26': 'me_mobilegridcell_26',
        'add': 'me_add',
        'notfound': 'me_notfound',
        'mobilelabel_31': 'me_mobilelabel_31'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["me_logout_onsuccess_mapping_0"] = {
        "homeScreen": "me",
        "directions": []
    };

    Apperyio.mappings["me_logout_onbeforesend_mapping_0"] = {
        "homeScreen": "me",
        "directions": [

        {
            "from_name": "userSessionToken",
            "from_type": "SESSION_STORAGE",

            "to_name": "logout",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['X-Appery-Session-Token']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["me_search_onsuccess_mapping_0"] = {
        "homeScreen": "me",
        "directions": [

        {
            "from_name": "search",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "me",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body'][i]",
                "target": "$['mobilegrid_18']"

            },

            {

                "source": "$['body'][i]['clubname']",
                "target": "$['mobilegrid_18']['clubname:text']"

            },

            {

                "source": "$['body'][i]['AdminName']",
                "target": "$['mobilegrid_18']['administrator:text']"

            }

            ]
        },

        {
            "from_name": "search",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "clubId",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body'][0]['_id']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "search",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "members",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body'][0]['Members']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["me_search_onbeforesend_mapping_0"] = {
        "homeScreen": "me",
        "directions": [

        {
            "from_name": "me",
            "from_type": "UI",

            "to_name": "search",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['clubnameinput:text']",
                "target_transformation": function(value) {
                    return '{"clubname":"' + value + '"}';
                },
                "target": "$['parameters']['where']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["me_addmembers_onsuccess_mapping_0"] = {
        "homeScreen": "me",
        "directions": []
    };

    Apperyio.mappings["me_addmembers_onbeforesend_mapping_0"] = {
        "homeScreen": "me",
        "directions": [

        {
            "from_name": "userSessionToken",
            "from_type": "SESSION_STORAGE",

            "to_name": "addmembers",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['X-Appery-Session-Token']"

            }

            ]
        },

        {
            "from_name": "members",
            "from_type": "SESSION_STORAGE",

            "to_name": "addmembers",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['Members']"

            }

            ]
        },

        {
            "from_name": "clubId",
            "from_type": "SESSION_STORAGE",

            "to_name": "addmembers",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['object_id']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["me_addclubs_onsuccess_mapping_0"] = {
        "homeScreen": "me",
        "directions": []
    };

    Apperyio.mappings["me_addclubs_onbeforesend_mapping_0"] = {
        "homeScreen": "me",
        "directions": [

        {
            "from_name": "memberof",
            "from_type": "SESSION_STORAGE",

            "to_name": "addclubs",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['MemberOf']"

            }

            ]
        },

        {
            "from_name": "userSessionToken",
            "from_type": "SESSION_STORAGE",

            "to_name": "addclubs",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['X-Appery-Session-Token']"

            }

            ]
        },

        {
            "from_name": "userID",
            "from_type": "SESSION_STORAGE",

            "to_name": "addclubs",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['object_id']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["me_memberof_onbeforesend_mapping_0"] = {
        "homeScreen": "me",
        "directions": [

        {
            "from_name": "userID",
            "from_type": "SESSION_STORAGE",

            "to_name": "memberof",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target_transformation": function(value) {
                    return '{"_id":"' + value + '"}';
                },
                "target": "$['parameters']['where']"

            }

            ]
        },

        {
            "from_name": "userSessionToken",
            "from_type": "SESSION_STORAGE",

            "to_name": "memberof",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['X-Appery-Session-Token']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["me_memberof_onsuccess_mapping_0"] = {
        "homeScreen": "me",
        "directions": [

        {
            "from_name": "memberof",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "memberof",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body'][0]['MemberOf']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "memberof",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "userID",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body'][0]['_id']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.logout = Apperyio.datasources.logout = new Apperyio.DataSource(UserInformation_logout_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["me_logout_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("me");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["me_logout_onsuccess_mapping_0"]);
            Apperyio.navigateTo('startScreen', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.search = Apperyio.datasources.search = new Apperyio.DataSource(UserInformation_UserType_query_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["me_search_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            if (jqXHR.responseText == "[]") {
                Apperyio("notfound").show();
            } else {
                Apperyio("mobilegrid_18").show();
            };

            Apperyio.refreshScreenFormElements("me");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["me_search_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.addmembers = Apperyio.datasources.addmembers = new Apperyio.DataSource(UserInformation_UserType_update_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["me_addmembers_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("me");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["me_addmembers_onsuccess_mapping_0"]);
            try {
                addclubs.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.addclubs = Apperyio.datasources.addclubs = new Apperyio.DataSource(UserInformation_UserType_update2_service_clone_1, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["me_addclubs_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("me");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["me_addclubs_onsuccess_mapping_0"]);
            if (sessionStorage.getItem('memberof') === null) sessionStorage.setItem('memberof', []);
            sessionStorage.setItem('stringversion', sessionStorage.getItem('memberof').toString());
            try {
                $a.c15r("clubslabel", "set", "text", $a.storage["stringversion"].get("$"))
            } catch (e) {
                console.error(e)
            };
            $('[id="me_panel_14"]').panel("close");
            var popupElement = Apperyio("alert");
            if (popupElement.popup("option", "positionTo") === "origin") {
                popupElement.popup("open", {
                    transition: "slidedown",
                    positionTo: "#" + $(this).attr("id")
                });
            } else {
                popupElement.popup("open", {
                    transition: "slidedown"
                });
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.memberof = Apperyio.datasources.memberof = new Apperyio.DataSource(UserInformation_UserType_query_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["me_memberof_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("me");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["me_memberof_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'me';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var me_onLoad = function() {
            me_elementsExtraJS();

            try {
                $a.c15r("usernamelabel", "set", "text", $a.storage["username"].get("$"))
            } catch (e) {
                console.error(e)
            };
            try {
                $a.c15r("passwordlabel", "set", "text", $a.storage["password"].get("$"))
            } catch (e) {
                console.error(e)
            };
            try {
                memberof.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
            if (sessionStorage.getItem('memberof').length === 0) {
                sessionStorage.setItem('stringversion', "");
            } else sessionStorage.setItem('stringversion', sessionStorage.getItem('memberof').toString());
            try {
                $a.c15r("clubslabel", "set", "text", $a.storage["stringversion"].get("$"))
            } catch (e) {
                console.error(e)
            };

            me_deviceEvents();
            me_windowEvents();
            me_elementsEvents();
        };

    // screen window events


    function me_windowEvents() {

        $('#me').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function me_deviceEvents() {
        document.addEventListener("deviceready", function() {

            $(document).bind("resume", function() {
                PushNotification.getPendingNotifications(function(status) {
                    var notifications = status.notifications;
                    for (var i = 0; i < notifications.length; ++i) {
                        PushNotification.notificationCallback(notifications[i]);
                    }
                });
            });

        });
    };

    // screen elements extra js


    function me_elementsExtraJS() {
        // screen (me) extra code

        /* alert */
        $("#me_alert").popup("option", "positionTo", "window");

    };

    // screen elements handler


    function me_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#me_mobileheader [name="logout"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        logout.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#me_mobileheader [name="logout"]');
        $(document).off("click", '#me_mobileheader [name="addclub"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio("clubnameinput").val("");
                    Apperyio("mobilegrid_18").hide();
                    Apperyio("notfound").hide();
                    $('[id="me_panel_14"]').panel("open");

                }
            },
        }, '#me_mobileheader [name="addclub"]');

        $(document).off("click", '#me_mobilefooter [name="metab"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('me', {
                        reverse: false
                    });

                }
            },
        }, '#me_mobilefooter [name="metab"]');
        $(document).off("click", '#me_mobilefooter [name="notify"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    setTimeout(function() {
                        window.location = 'Notifications.html';
                    }, 0);

                }
            },
        }, '#me_mobilefooter [name="notify"]');
        $(document).off("click", '#me_mobilefooter [name="calendar"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    setTimeout(function() {
                        window.location = 'yourEvents.html';
                    }, 0);

                }
            },
        }, '#me_mobilefooter [name="calendar"]');

        $(document).off("click", '#me_panel_14 [name="searchbutton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        search.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    Apperyio("notfound").hide();

                }
            },
        }, '#me_panel_14 [name="searchbutton"]');

        $(document).off("click", '#me_panel_14 [name="add"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var arr = Apperyio.storage.members.get() || [];
                    arr.push(sessionStorage.getItem('username'));
                    Apperyio.storage.members.set(arr);
                    sessionStorage.setItem('clubs', Apperyio('clubnameinput').val());
                    var arr = Apperyio.storage.memberof.get() || [];
                    arr.push(sessionStorage.getItem('clubs'));
                    Apperyio.storage.memberof.set(arr);
                    try {
                        addmembers.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#me_panel_14 [name="add"]');

    };

    $(document).off("pagebeforeshow", "#me").on("pagebeforeshow", "#me", function(event, ui) {
        Apperyio.CurrentScreen = "me";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    me_onLoad();
};

$(document).off("pagecreate", "#me").on("pagecreate", "#me", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    me_js();
});