/*
 * JS for Notify generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '96bf557e-32e1-4d20-ac3a-5655fb026817';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Club",
    "location": "Club.html"
}, {
    "name": "GitHub_Img",
    "location": "GitHub_Img.html"
}, {
    "name": "GitHub_File",
    "location": "GitHub_File.html"
}, {
    "name": "ExamplePage1426375367500",
    "location": "ExamplePage1426375367500.html"
}, {
    "name": "GitHub_Gist",
    "location": "GitHub_Gist.html"
}, {
    "name": "me",
    "location": "me.html"
}, {
    "name": "GitHub_Repo",
    "location": "GitHub_Repo.html"
}, {
    "name": "Notify",
    "location": "Notify.html"
}, {
    "name": "signIn",
    "location": "signIn.html"
}, {
    "name": "Calendar",
    "location": "Calendar.html"
}, {
    "name": "signUp",
    "location": "signUp.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "Notifications",
    "location": "Notifications.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "GitHub_Git",
    "location": "GitHub_Git.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "GitHub_Search",
    "location": "GitHub_Search.html"
}, {
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}, {
    "name": "yourEvents",
    "location": "yourEvents.html"
}];

function Notify_js() {
    
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'logout': 'Notify_logout',
        'headerinput': 'Notify_headerinput',
        'messageinput': 'Notify_messageinput',
        'send': 'Notify_send',
        'mobilenavbar_2': 'Notify_mobilenavbar_2',
        'club': 'Notify_club',
        'notify': 'Notify_notify',
        'calendar': 'Notify_calendar',
        'sent': 'Notify_sent'
    };
    
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    
    /*
     * Nonvisual components
     */
    
    Apperyio.mappings = Apperyio.mappings || {};
    
    Apperyio.mappings["Notify_logout_clone_5_onsuccess_mapping_0"] = {
        "homeScreen": "Notify",
        "directions": []
    };
    
    Apperyio.mappings["Notify_logout_clone_5_onbeforesend_mapping_0"] = {
        "homeScreen": "Notify",
        "directions": [
            
            {
                "from_name": "userSessionToken",
                "from_type": "SESSION_STORAGE",
                
                "to_name": "logout_clone_5",
                "to_type": "SERVICE_REQUEST",
                
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}"
                    },
                    "parameters": {},
                    "body": null
                },
                
                "mappings": [
                    
                    {
                        
                        "source": "$",
                        "target": "$['headers']['X-Appery-Session-Token']"
                        
                    }
                    
                ]
            }
            
        ]
    };
    
    Apperyio.mappings["Notify_sendmessage_onsuccess_mapping_0"] = {
        "homeScreen": "Notify",
        "directions": []
    };
    
    Apperyio.mappings["Notify_sendmessage_onbeforesend_mapping_0"] = {
        "homeScreen": "Notify",
        "directions": [
            
            {
                "from_name": "userID",
                "from_type": "SESSION_STORAGE",
                
                "to_name": "sendmessage",
                "to_type": "SERVICE_REQUEST",
                
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": null
                },
                
                "mappings": [
                    
                    {
                        
                        "source": "$",
                        "target": "$['body']['object_id']"
                        
                    }
                    
                ]
            },
            
            {
                "from_name": "headers",
                "from_type": "SESSION_STORAGE",
                
                "to_name": "sendmessage",
                "to_type": "SERVICE_REQUEST",
                
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": null
                },
                
                "mappings": [
                    
                    {
                        
                        "source": "$",
                        "target": "$['body']['Headers']"
                        
                    },
                    
                    {
                        
                        "source": "$[i]",
                        "target": "$['body']['Headers'][i]"
                        
                    }
                    
                ]
            },
            
            {
                "from_name": "messages",
                "from_type": "SESSION_STORAGE",
                
                "to_name": "sendmessage",
                "to_type": "SERVICE_REQUEST",
                
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": null
                },
                
                "mappings": [
                    
                    {
                        
                        "source": "$",
                        "target": "$['body']['Messages']"
                        
                    },
                    
                    {
                        
                        "source": "$[i]",
                        "target": "$['body']['Messages'][i]"
                        
                    }
                    
                ]
            },
            
            {
                "from_name": "dates",
                "from_type": "SESSION_STORAGE",
                
                "to_name": "sendmessage",
                "to_type": "SERVICE_REQUEST",
                
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": null
                },
                
                "mappings": [
                    
                    {
                        
                        "source": "$",
                        "target": "$['body']['Dates']"
                        
                    },
                    
                    {
                        
                        "source": "$[i]",
                        "target": "$['body']['Dates'][i]"
                        
                    }
                    
                ]
            }
            
        ]
    };
    
    Apperyio.mappings["Notify_getinfo_onsuccess_mapping_0"] = {
        "homeScreen": "Notify",
        "directions": [
            
            {
                "from_name": "getinfo",
                "from_type": "SERVICE_RESPONSE",
                
                "to_name": "messages",
                "to_type": "SESSION_STORAGE",
                
                "mappings": [
                    
                    {
                        
                        "source": "$['body'][0]['Messages']",
                        "target": "$"
                        
                    },
                    
                    {
                        
                        "source": "$['body'][0]['Messages'][i]",
                        "target": "$[i]"
                        
                    }
                    
                ]
            },
            
            {
                "from_name": "getinfo",
                "from_type": "SERVICE_RESPONSE",
                
                "to_name": "headers",
                "to_type": "SESSION_STORAGE",
                
                "mappings": [
                    
                    {
                        
                        "source": "$['body'][0]['Headers']",
                        "target": "$"
                        
                    },
                    
                    {
                        
                        "source": "$['body'][0]['Headers'][i]",
                        "target": "$[i]"
                        
                    }
                    
                ]
            },
            
            {
                "from_name": "getinfo",
                "from_type": "SERVICE_RESPONSE",
                
                "to_name": "dates",
                "to_type": "SESSION_STORAGE",
                
                "mappings": [
                    
                    {
                        
                        "source": "$['body'][0]['Dates']",
                        "target": "$"
                        
                    },
                    
                    {
                        
                        "source": "$['body'][0]['Dates'][i]",
                        "target": "$[i]"
                        
                    }
                    
                ]
            }
            
        ]
    };
    
    Apperyio.mappings["Notify_getinfo_onbeforesend_mapping_0"] = {
        "homeScreen": "Notify",
        "directions": [
            
            {
                "from_name": "userID",
                "from_type": "SESSION_STORAGE",
                
                "to_name": "getinfo",
                "to_type": "SERVICE_REQUEST",
                
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}"
                    },
                    "parameters": {},
                    "body": null
                },
                
                "mappings": [
                    
                    {
                        
                        "source": "$",
                        "target_transformation": function(value) {
                            return '{"_id":"' + value + '"}';
                        },
                        "target": "$['parameters']['where']"
                        
                    }
                    
                ]
            }
            
        ]
    };
    
    Apperyio.datasources = Apperyio.datasources || {};
    
    window.logout_clone_5 = Apperyio.datasources.logout_clone_5 = new Apperyio.DataSource(UserInformation_logout_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Notify_logout_clone_5_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            
            Apperyio.refreshScreenFormElements("Notify");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Notify_logout_clone_5_onsuccess_mapping_0"]);
            Apperyio.navigateTo('startScreen', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    
    window.sendmessage = Apperyio.datasources.sendmessage = new Apperyio.DataSource(UserInformation_UserType_update3_service_clone_2, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Notify_sendmessage_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            
            Apperyio.refreshScreenFormElements("Notify");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Notify_sendmessage_onsuccess_mapping_0"]);
            Apperyio("headerinput").val("");
            Apperyio("headerinput").attr("placeholder", "Header");
            Apperyio("messageinput").val("");
            Apperyio("messageinput").attr("placeholder", "Message");
            var popupElement = Apperyio("mobilepopup_31");
            if (popupElement.popup("option", "positionTo") === "origin") {
                popupElement.popup("open", {
                    transition: "fade",
                    positionTo: "#" + $(this).attr("id")
                });
            } else {
                popupElement.popup("open", {
                    transition: "fade"
                });
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    
    window.getinfo = Apperyio.datasources.getinfo = new Apperyio.DataSource(UserInformation_UserType_query_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Notify_getinfo_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            
            Apperyio.refreshScreenFormElements("Notify");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Notify_getinfo_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    
    Apperyio.CurrentScreen = 'Notify';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);
    
    /*
     * Events and handlers
     */
    
    // On Load
    var Notify_onLoad = function() {
        Notify_elementsExtraJS();
        var arr = JSON.parse(sessionStorage.getItem('messages'));
        var arr2 = JSON.parse(sessionStorage.getItem('headers'));
        var arr3 = JSON.parse(sessionStorage.getItem('dates'));
        Apperyio("mobilecontainer").append("<div id='div' style='width: 100%; height: 220px; overflow: scroll'></div>");
        div.setAttribute("id", "div");
        var index;
        if(arr!==null){
            var table = document.createElement("table");
            table.setAttribute("id", "list");
            table.setAttribute("class", "list");
            table.setAttribute("border", "1px");
            table.setAttribute("padding", "5px");
            table.setAttribute("rules", "rows");
            for(index = 0; index < arr.length; index++) {
                var item1 = arr2[index];
                var item2 = arr3[index];
                var item3 = arr[index];
                var row = table.insertRow(0);
                row.innerHTML = '<div id="name" class="row"><p data-name="header" name="header" style=" padding-left: 8px; padding-right: 8px"><strong>'+item1+'</strong></p><p data-name="datesent" name="datasent" style=" padding-left: 8px; padding-right: 8px">Sent at: <em>'+item2+'</em></p><p data-name="message" name="message" style=" padding-left: 8px; padding-right: 8px">'+item3+'</p></div>';
            }
            $('#div').append(table);
        }
        else{
            $('#div').append('<p style="color: gray"><em>No Notifications</em></p>');
        }
        Notify_deviceEvents();
        Notify_windowEvents();
        Notify_elementsEvents();
    };
    
    // screen window events
    
    
    function Notify_windowEvents() {
        
        $('#Notify').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        
    };
    
    // device events
    
    
    function Notify_deviceEvents() {
        document.addEventListener("deviceready", function() {
            
            $(document).bind("resume", function() {
                PushNotification.getPendingNotifications(function(status) {
                    var notifications = status.notifications;
                    for (var i = 0; i < notifications.length; ++i) {
                        PushNotification.notificationCallback(notifications[i]);
                    }
                });
            });
            
        });
    };
    
    // screen elements extra js
    
    
    function Notify_elementsExtraJS() {
        // screen (Notify) extra code
        
        /* mobilepopup_31 */
        $("#Notify_mobilepopup_31").popup("option", "positionTo", "window");
        
    };
    
    // screen elements handler
    
    
    function Notify_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        
        $(document).off("click", '#Notify_mobileheader [name="logout"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        logout_clone_5.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    
                }
            },
        }, '#Notify_mobileheader [name="logout"]');
        
        $(document).off("click", '#Notify_mobilecontainer [name="send"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        getinfo.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    var arr = Apperyio.storage.messages.get() || [];
                    arr.push(Apperyio("messageinput").val());
                    Apperyio.storage.messages.set(arr);
                    
                    var arr2 = Apperyio.storage.headers.get() || [];
                    arr2.push(Apperyio("headerinput").val());
                    Apperyio.storage.headers.set(arr2);
                    
                    var arr3 = Apperyio.storage.dates.get() || [];
                    var dt = new Date();
                    h = (dt.getHours()<10?'0':'') + dt.getHours();
                    m = (dt.getMinutes()<10?'0':'') + dt.getMinutes();
                    arr3.push(dt.getFullYear() + "-" + (dt.getMonth() + 1) + "-" + dt.getDate()+' '+h + ':' + m);
                    Apperyio.storage.dates.set(arr3);
                    var arr = JSON.parse(sessionStorage.getItem('messages'));
                    var arr2 = JSON.parse(sessionStorage.getItem('headers'));
                    var arr3 = JSON.parse(sessionStorage.getItem('dates'));
                    document.getElementById("div").remove();
                    Apperyio("mobilecontainer").append("<div id='div' style='width: 100%; height: 220px; overflow: scroll'></div>");
                    var table = document.createElement("table");
                    table.setAttribute("id", "list");
                    table.setAttribute("class", "list");
                    table.setAttribute("border", "1px");
                    table.setAttribute("padding", "5px");
                    table.setAttribute("rules", "rows");
                    var index;
                    for(index = 0; index < arr.length; index++) {
                        var item1 = arr2[index];
                        var item2 = arr3[index];
                        var item3 = arr[index];
                        var row = table.insertRow(0);
                        row.innerHTML = '<div id="name" class="row"><p data-name="header" name="header" style=" padding-left: 8px; padding-right: 8px"><strong>'+item1+'</strong></p><p data-name="datesent" name="datasent" style=" padding-left: 8px; padding-right: 8px">Sent at: <em>'+item2+'</em></p><p data-name="message" name="message" style=" padding-left: 8px; padding-right: 8px">'+item3+'</p></div>';
                    }
                    $('#div').append(table);
                    try {
                        sendmessage.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    
                }
            },
        }, '#Notify_mobilecontainer [name="send"]');
        
        $(document).off("click", '#Notify_mobilefooter [name="notify"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Notify', {
                        reverse: false
                    });
                    
                }
            },
        }, '#Notify_mobilefooter [name="notify"]');
        $(document).off("click", '#Notify_mobilefooter [name="club"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    setTimeout(function() {
                        window.location = 'Club.html';
                    }, 0);
                    
                }
            },
        }, '#Notify_mobilefooter [name="notify"]');
        $(document).off("click", '#Notify_mobilefooter [name="calendar"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    setTimeout(function() {
                        window.location = 'Calendar.html';
                    }, 0);
                    
                }
            },
        }, '#Notify_mobilefooter [name="calendar"]');
        
    };
    
    $(document).off("pagebeforeshow", "#Notify").on("pagebeforeshow", "#Notify", function(event, ui) {
        Apperyio.CurrentScreen = "Notify";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });
    
    Notify_onLoad();
};

$(document).off("pagecreate", "#Notify").on("pagecreate", "#Notify", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Notify_js();
});