/*
 * JS for signIn generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '96bf557e-32e1-4d20-ac3a-5655fb026817';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Club",
    "location": "Club.html"
}, {
    "name": "GitHub_Img",
    "location": "GitHub_Img.html"
}, {
    "name": "GitHub_File",
    "location": "GitHub_File.html"
}, {
    "name": "ExamplePage1426375367500",
    "location": "ExamplePage1426375367500.html"
}, {
    "name": "GitHub_Gist",
    "location": "GitHub_Gist.html"
}, {
    "name": "me",
    "location": "me.html"
}, {
    "name": "GitHub_Repo",
    "location": "GitHub_Repo.html"
}, {
    "name": "signIn",
    "location": "signIn.html"
}, {
    "name": "Notify",
    "location": "Notify.html"
}, {
    "name": "Calendar",
    "location": "Calendar.html"
}, {
    "name": "signUp",
    "location": "signUp.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "Notifications",
    "location": "Notifications.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "GitHub_Git",
    "location": "GitHub_Git.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "GitHub_Search",
    "location": "GitHub_Search.html"
}, {
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}, {
    "name": "yourEvents",
    "location": "yourEvents.html"
}];

function signIn_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'backbutton': 'signIn_backbutton',
        'Username': 'signIn_Username',
        'usernameInput': 'signIn_usernameInput',
        'Password': 'signIn_Password',
        'passwordInput': 'signIn_passwordInput',
        'login': 'signIn_login',
        'wrong': 'signIn_wrong'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["signIn_login_onsuccess_mapping_0"] = {
        "homeScreen": "signIn",
        "directions": [

        {
            "from_name": "signIn",
            "from_type": "UI",

            "to_name": "username",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['usernameInput:text']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "login",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "userSessionToken",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['sessionToken']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "login",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "userID",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['_id']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["signIn_login_onbeforesend_mapping_0"] = {
        "homeScreen": "signIn",
        "directions": [

        {
            "from_name": "signIn",
            "from_type": "UI",

            "to_name": "login",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['usernameInput:text']",
                "target": "$['parameters']['username']"

            },

            {

                "source": "$['passwordInput:text']",
                "target": "$['parameters']['password']"

            }

            ]
        },

        {
            "from_name": "signIn",
            "from_type": "UI",

            "to_name": "password",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['passwordInput:text']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "signIn",
            "from_type": "UI",

            "to_name": "username",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['usernameInput:text']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["signIn_admin_onsuccess_mapping_0"] = {
        "homeScreen": "signIn",
        "directions": [

        {
            "from_name": "admin",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "name",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body'][0]['Administrator']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "admin",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "memberof",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body'][0]['MemberOf']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "admin",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "members",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body'][0]['Members']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "admin",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "userID",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body'][0]['_id']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "admin",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "messages",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body'][0]['Messages']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "admin",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "headers",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body'][0]['Headers']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "admin",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "dates",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body'][0]['Dates']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "admin",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "clubId",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body'][0]['clubname']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["signIn_admin_onbeforesend_mapping_0"] = {
        "homeScreen": "signIn",
        "directions": [

        {
            "from_name": "userSessionToken",
            "from_type": "SESSION_STORAGE",

            "to_name": "admin",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['X-Appery-Session-Token']"

            }

            ]
        },

        {
            "from_name": "username",
            "from_type": "SESSION_STORAGE",

            "to_name": "admin",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target_transformation": function(value) {
                    return '{"AdminName":"' + value + '"}';
                },
                "target": "$['parameters']['where']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.login = Apperyio.datasources.login = new Apperyio.DataSource(UserInformation_login_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["signIn_login_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("signIn");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["signIn_login_onsuccess_mapping_0"]);
            try {
                admin.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            var popupElement = Apperyio("mobilepopup_2");
            if (popupElement.popup("option", "positionTo") === "origin") {
                popupElement.popup("open", {
                    transition: "none",
                    positionTo: "#" + $(this).attr("id")
                });
            } else {
                popupElement.popup("open", {
                    transition: "none"
                });
            };
        }
    });

    window.admin = Apperyio.datasources.admin = new Apperyio.DataSource(UserInformation_UserType_query_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["signIn_admin_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            if (jqXHR.responseText == "[]") {
                alert("hello");
            };

            Apperyio.refreshScreenFormElements("signIn");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["signIn_admin_onsuccess_mapping_0"]);
            if (sessionStorage.getItem('name') === "false") {
                return Apperyio.navigateTo('me', {});
            } else if (sessionStorage.getItem('name') === "true") {
                return Apperyio.navigateTo('Club', {});
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'signIn';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var signIn_onLoad = function() {
            signIn_elementsExtraJS();

            signIn_deviceEvents();
            signIn_windowEvents();
            signIn_elementsEvents();
        };

    // screen window events


    function signIn_windowEvents() {

        $('#signIn').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function signIn_deviceEvents() {
        document.addEventListener("deviceready", function() {

            $(document).bind("resume", function() {
                PushNotification.getPendingNotifications(function(status) {
                    var notifications = status.notifications;
                    for (var i = 0; i < notifications.length; ++i) {
                        PushNotification.notificationCallback(notifications[i]);
                    }
                });
            });

        });
    };

    // screen elements extra js


    function signIn_elementsExtraJS() {
        // screen (signIn) extra code

        /* mobilepopup_2 */
        $("#signIn_mobilepopup_2").popup("option", "positionTo", "window");

    };

    // screen elements handler


    function signIn_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#signIn_mobileheader [name="backbutton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        reverse: false
                    });

                }
            },
        }, '#signIn_mobileheader [name="backbutton"]');

        $(document).off("click", '#signIn_mobilecontainer [name="login"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        login.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#signIn_mobilecontainer [name="login"]');

    };

    $(document).off("pagebeforeshow", "#signIn").on("pagebeforeshow", "#signIn", function(event, ui) {
        Apperyio.CurrentScreen = "signIn";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    signIn_onLoad();
};

$(document).off("pagecreate", "#signIn").on("pagecreate", "#signIn", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    signIn_js();
});