/*
 * JS for signUp generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '96bf557e-32e1-4d20-ac3a-5655fb026817';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Club",
    "location": "Club.html"
}, {
    "name": "GitHub_Img",
    "location": "GitHub_Img.html"
}, {
    "name": "GitHub_File",
    "location": "GitHub_File.html"
}, {
    "name": "ExamplePage1426375367500",
    "location": "ExamplePage1426375367500.html"
}, {
    "name": "GitHub_Gist",
    "location": "GitHub_Gist.html"
}, {
    "name": "me",
    "location": "me.html"
}, {
    "name": "GitHub_Repo",
    "location": "GitHub_Repo.html"
}, {
    "name": "signIn",
    "location": "signIn.html"
}, {
    "name": "Notify",
    "location": "Notify.html"
}, {
    "name": "Calendar",
    "location": "Calendar.html"
}, {
    "name": "signUp",
    "location": "signUp.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "Notifications",
    "location": "Notifications.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "GitHub_Git",
    "location": "GitHub_Git.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "GitHub_Search",
    "location": "GitHub_Search.html"
}, {
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}, {
    "name": "yourEvents",
    "location": "yourEvents.html"
}];

function signUp_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'backbutton': 'signUp_backbutton',
        'Username': 'signUp_Username',
        'usernameenter': 'signUp_usernameenter',
        'Password': 'signUp_Password',
        'passwordenter': 'signUp_passwordenter',
        'chooseaccount': 'signUp_chooseaccount',
        'administrator': 'signUp_administrator',
        'clubmember': 'signUp_clubmember',
        'signup': 'signUp_signup',
        'clubname': 'signUp_clubname',
        'clubnameenter': 'signUp_clubnameenter',
        'clubnameset': 'signUp_clubnameset',
        'accounterror': 'signUp_accounterror'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["signUp_signup_onbeforesend_mapping_0"] = {
        "homeScreen": "signUp",
        "directions": [

        {
            "from_name": "signUp",
            "from_type": "UI",

            "to_name": "signup",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['usernameenter:text']",
                "target": "$['body']['username']"

            },

            {

                "source": "$['passwordenter:text']",
                "target": "$['body']['password']"

            }

            ]
        },

        {
            "from_name": "signUp",
            "from_type": "UI",

            "to_name": "username",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['usernameenter:text']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "signUp",
            "from_type": "UI",

            "to_name": "password",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['passwordenter:text']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["signUp_signup_onsuccess_mapping_0"] = {
        "homeScreen": "signUp",
        "directions": [

        {
            "from_name": "signup",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "userSessionToken",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['sessionToken']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "signup",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "username",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['username']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["signUp_accounttype_onbeforesend_mapping_0"] = {
        "homeScreen": "signUp",
        "directions": [

        {
            "from_name": "signUp",
            "from_type": "UI",

            "to_name": "accounttype",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "Administrator": false,
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$['administrator:selected']",
                "target": "$['body']['Administrator']"

            },

            {

                "source": "$['clubnameenter:text']",
                "target": "$['body']['clubname']"

            },

            {

                "source": "$['usernameenter:text']",
                "target": "$['body']['AdminName']"

            }

            ]
        },

        {
            "from_name": "signUp",
            "from_type": "UI",

            "to_name": "name",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['administrator:selected']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "signUp",
            "from_type": "UI",

            "to_name": "clubId",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['clubnameenter:text']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["signUp_accounttype_onsuccess_mapping_0"] = {
        "homeScreen": "signUp",
        "directions": [

        {
            "from_name": "accounttype",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "userID",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['_id']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.signup = Apperyio.datasources.signup = new Apperyio.DataSource(UserInformation_signup_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["signUp_signup_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("signUp");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["signUp_signup_onsuccess_mapping_0"]);
            try {
                accounttype.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            var popupElement = Apperyio("mobilepopup_3");
            if (popupElement.popup("option", "positionTo") === "origin") {
                popupElement.popup("open", {
                    transition: "none",
                    positionTo: "#" + $(this).attr("id")
                });
            } else {
                popupElement.popup("open", {
                    transition: "none"
                });
            };
        }
    });

    window.accounttype = Apperyio.datasources.accounttype = new Apperyio.DataSource(UserInformation_UserType_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["signUp_accounttype_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("signUp");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["signUp_accounttype_onsuccess_mapping_0"]);
            sessionStorage.setItem('memberof', []);
            sessionStorage.setItem('members', []);
            sessionStorage.setItem('stringversion', "");
            if (sessionStorage.getItem('name') === "false") return Apperyio.navigateTo('me', {});

            else if (sessionStorage.getItem('name') === "true") {
                Apperyio.navigateTo('Club', {});
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            var popupElement = Apperyio("mobilepopup_3");
            if (popupElement.popup("option", "positionTo") === "origin") {
                popupElement.popup("open", {
                    transition: "none",
                    positionTo: "#" + $(this).attr("id")
                });
            } else {
                popupElement.popup("open", {
                    transition: "none"
                });
            };
        }
    });

    Apperyio.CurrentScreen = 'signUp';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var signUp_onLoad = function() {
            signUp_elementsExtraJS();

            signUp_deviceEvents();
            signUp_windowEvents();
            signUp_elementsEvents();
        };

    // screen window events


    function signUp_windowEvents() {

        $('#signUp').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function signUp_deviceEvents() {
        document.addEventListener("deviceready", function() {

            $(document).bind("resume", function() {
                PushNotification.getPendingNotifications(function(status) {
                    var notifications = status.notifications;
                    for (var i = 0; i < notifications.length; ++i) {
                        PushNotification.notificationCallback(notifications[i]);
                    }
                });
            });

        });
    };

    // screen elements extra js


    function signUp_elementsExtraJS() {
        // screen (signUp) extra code

        /* clubnamepopup */
        $("#signUp_clubnamepopup").popup("option", "positionTo", "window");

        /* mobilepopup_3 */
        $("#signUp_mobilepopup_3").popup("option", "positionTo", "window");

    };

    // screen elements handler


    function signUp_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#signUp_mobileheader [name="backbutton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        reverse: false
                    });

                }
            },
        }, '#signUp_mobileheader [name="backbutton"]');

        $(document).off("click", '#signUp_mobilecontainer [name="administrator"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var popupElement = Apperyio("clubnamepopup");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "fade",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "fade"
                        });
                    };

                }
            },
        }, '#signUp_mobilecontainer [name="administrator"]');

        $(document).off("click", '#signUp_mobilecontainer [name="signup"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        signup.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#signUp_mobilecontainer [name="signup"]');

        $(document).off("click", '#signUp_clubnamepopup [name="clubnameset"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('clubnamepopup').popup('close');

                }
            },
        }, '#signUp_clubnamepopup [name="clubnameset"]');

    };

    $(document).off("pagebeforeshow", "#signUp").on("pagebeforeshow", "#signUp", function(event, ui) {
        Apperyio.CurrentScreen = "signUp";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    signUp_onLoad();
};

$(document).off("pagecreate", "#signUp").on("pagecreate", "#signUp", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    signUp_js();
});